### ISSUE TITLE
The problem with input and weight

### ISSUE THREAD

**Issue by RY-97** [SsGood/MMGL#12] opened 2023-06-15 01:11 UTC
<img width="668" alt="无标题" src="https://github.com/SsGood/MMGL/assets/88662555/169c04f7-63c6-4f6c-85b4-e6c6047276c4">

**Comment by SsGood** [comment] 2023-06-15 02:42
I‘m sorry I cannot reproduce your problem since the codes work well on my server when I run the code for ABIDE dataset. 
According to the content you post, I guess the features are not loaded as expected. In the top of your image, it shows the data shape is (871, 321) while the runtime error shows that the shape of the loaded feature is (871, 256). 
Could you provide more details?

**Comment by RY-97** [comment] 2023-06-15 02:45
I just ran with the ABIDE dataset, and this error occurred

**Comment by SsGood** [comment] 2023-06-15 03:40
You can copy the folder 'MMGL/data' to the path 'MMGL/MMGL_transductive/data', and re-run the '.sh' file under the folder 'MMGL/MMGL_transductive/'

**Comment by SsGood** [comment] 2023-06-15 08:17
I will close the issue, you could re-open it if the issue still exists.

**Closed as completed by SsGood** 2023-06-15 08:17 UTC
